export const constants: constTypes = {
  ACTIVE_DEPOSIT_DURATION: 400,
  CONTRACT: 'kompwnd',
  REFERRAL_PERCENTAGE: 0.1,
  FEE_PERCENTAGE: 0.1,
  ROLL_PERCENTAGE: 0.9,
  DAILY_REWARD_PERCENTAGE: 0.005,
  CLAIM_DIV_THRESHOLD: 50,
  ROLL_DIV_THRESHOLD: 40,
  DEPOSIT_THRESHOLD: 10,
  ZERO_KPW: '0.0000 KPW',
  DECIMALS: 4,
  DAY_IN_MILLISECONDS: 1000 * 60 * 60 * 24,
} as const;

type constTypes = {
  ACTIVE_DEPOSIT_DURATION: number;
  CONTRACT: string;
  REFERRAL_PERCENTAGE: number;
  FEE_PERCENTAGE: number;
  ROLL_PERCENTAGE: number;
  DAILY_REWARD_PERCENTAGE: number;
  CLAIM_DIV_THRESHOLD: number;
  DEPOSIT_THRESHOLD: number;
  ROLL_DIV_THRESHOLD: number;
  ZERO_KPW: string;
  DECIMALS: number;
  DAY_IN_MILLISECONDS: number;
};
